# mode
adapt: false
use_pretrained: false
use_mlp: false

# dirs
display_name: baseline_original
adapt_dataset_path_dir: push_t_blue_dataset
dataset_path_dir: push_t_blue_dataset
models_save_dir: outputs/trained_models_baseline0
output_dir: outputs/output_baseline0

# hyperparams
num_epochs: 300
num_diffusion_iters: 100
num_tests: 50
num_vis_demos: 3
num_train_demos: 500
num_warmup_steps: 500
pred_horizon: 16
obs_horizon: 2
action_horizon: 8
max_steps: 300
eval_epoch: 20
lr: 0.0001
weight_decay: 0.000001
batch_size: 64
resize_scale: 224
wandb: true
verbose: false
