# mode
eval_mode: 1 # 1 or 2
use_pretrained: True

# dirs
display_name: baseline_original
dataset_path: push_t_dataset/domain18.zarr
models_save_dir: outputs/trained_models_baseline0
domain_id: 18

# hyperparams
num_epochs: 500
num_diffusion_iters: 100
num_train_demos: 500
num_warmup_steps: 500
pred_horizon: 16
obs_horizon: 2
action_horizon: 8
max_steps: 300
eval_epoch: 20
lr: 0.0001
weight_decay: 0.000001
batch_size: 64
wandb: true
verbose: false
vision_encoder: resnet # resnet, clip or dinov2
ratio: 0.9 # percent of dataset that is split into training data
