# mode
eval_mode: 1 # 1 or 2
use_pretrained: True

# foundation model
backbone: 'ViT-B-32'
weights: laion2b_s34b_b79k

# dirs
display_name: baseline_test_mode1
dataset_path: /n/netscratch/hankyang_lab/Lab/alex/push_t/domain18.zarr
models_save_dir: outputs/trained_models_test
domain_id: 18

# hyperparams
num_epochs: 1
num_diffusion_iters: 100
num_train_demos: 500
num_warmup_steps: 500
pred_horizon: 16
obs_horizon: 2
action_horizon: 8
max_steps: 300
eval_epoch: 1
lr: 0.0001
weight_decay: 0.000001
batch_size: 64
wandb: false
verbose: false
vision_encoder: clip # resnet, clip or dinov2
ratio: 0.9 # percent of dataset that is split into training data
